version: '3.9'

services:
  api:
    build:
      context: ./backend
    restart: always
    ports:
      - 5000:5000
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - API_KEY=AIzaSyAJ2fn0v3ww_5Q_USwFIhSX30LGBu9PPfM

networks:
  api-network:
    external: true
