version: '3.9'

services:
  api:
    build:
      context: ./backend
    restart: always
    ports:
      - 5000:5000
    environment:
      - DB_USER=chatuser
      - DB_PASSWORD=deaR89l5twuuvW45
      - API_KEY=AIzaSyDgcXeFjCbuGfv_wiG_ZKO9vZ-DFiPCCE4

networks:
  api-network:
    external: true
